const MODULES = [
  ['strategy','00','Strategy OS'],
  ['intelligence','01','Command Intelligence'],
  ['today','02','Today Action Board'],
  ['war','03','Sales War Room v2'],
  ['offers','04','Offer Ladder'],
  ['outreach','05','Outreach Vault'],
  ['medspa','06','MedSpa Campaign'],
  ['audit','07','Client Audit Generator'],
  ['closeTemplates','08','Close Room Templates'],
  ['demos','09','Demo Gallery'],
  ['repurpose','10','Content Repurposing'],
  ['cases','11','Case Study Templates'],
  ['pitch','12','One-Click Pitch Packs'],
  ['workflow','13','Audit → Demo → Pitch'],
  ['revenue','14','Revenue Forecast Simulator'],
  ['briefing','15','Morning Briefing'],
  ['proof','16','Proof Vault'],
  ['portfolio','17','Public Portfolio Page'],
  ['close','18','Client Close Room'],
  ['usage','∞','Usage Saver']
];
const state={leads:[], automations:[], growth:null, premium:null, active:'strategy', selected:null};
const $=s=>document.querySelector(s);
const fmt=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show-toast');setTimeout(()=>t.classList.remove('show-toast'),2400)}
async function init(){
  state.leads=await fetch('./data/leads.json').then(r=>r.json());
  state.automations=await fetch('./data/automations.json').then(r=>r.json());
  state.growth=await fetch('./data/stratos_growth_system.json').then(r=>r.json());
  state.premium=await fetch('./data/stratos_premium_ops.json').then(r=>r.json());
  state.selected=state.leads.slice().sort((a,b)=>b.score-a.score)[0];
  renderNav(); route(location.hash.replace('#','')||'strategy');
  window.addEventListener('hashchange',()=>route(location.hash.replace('#','')||'strategy'));
  $('#briefBtn').onclick=()=>{location.hash='briefing'; toast('Morning briefing generated from current lead board.')};
  $('#exportBtn').onclick=exportSnapshot;
}
function renderNav(){ $('#nav').innerHTML=MODULES.map(([id,num,name])=>`<button class="nav-btn" data-id="${id}"><span>${name}</span><small>${num}</small></button>`).join(''); document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{location.hash=b.dataset.id}); }
function route(id){state.active=id; document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.id===id)); const mod=MODULES.find(m=>m[0]===id)||MODULES[0]; $('#pageTitle').textContent=mod[2]; ({strategy,intelligence,today,war,offers,outreach,medspa,audit,closeTemplates,demos,repurpose,cases,pitch,workflow,revenue,briefing,proof,portfolio,close,usage}[mod[0]]||strategy)();}
function metrics(){const leads=state.leads, hot=leads.filter(l=>l.score>=88).length, pipe=leads.reduce((a,l)=>a+l.estBookings*l.avgValue,0); return `<div class="grid cols-4"><div class="card metric"><span>Total Leads</span><b>${leads.length}</b></div><div class="card metric"><span>Hot Leads 88+</span><b>${hot}</b></div><div class="card metric"><span>Projected Upside</span><b>${fmt(pipe)}</b></div><div class="card metric"><span>Execution Mode</span><b>Local-first</b></div></div>`}
function leadOptions(){return state.leads.map(l=>`<option value="${l.id}">${esc(l.business)} · ${esc(l.industry)} · ${l.score}</option>`).join('')}
function selectLead(id){state.selected=state.leads.find(l=>l.id===id)||state.leads[0]}
function copy(cmd){navigator.clipboard&&navigator.clipboard.writeText(cmd); toast('Copied command')}
function strategy(){
 const top=state.leads.slice().sort((a,b)=>b.score-a.score).slice(0,3);
 const ops=[['Absorb','Blueprint vault, live project state, lead data, proof, offers'],['Improve','Upgrade site/demo/close-room assets using deterministic generators'],['Integrate','Dashboard ⇄ website ⇄ demos ⇄ pitch kits ⇄ local AI ⇄ deploy prep'],['Test','Node/Python validators, browser smoke, Ollama health, manifest checks'],['Ship','Static/Vercel-ready package + local command center runbook']];
 const commands=[['Full rebuild/test','python3 scripts/run_all.py'],['Public site only','python3 scripts/build_public_site.py'],['Close rooms','python3 scripts/generate_close_rooms.py'],['Morning briefing','python3 scripts/generate_morning_briefing.py'],['Deploy manifest','python3 scripts/deploy_prep.py'],['Local Hermes draft',`hermes -p stratos-local chat -t terminal,file -q "Using /Users/bradleydipaolo/stratos-ai/hermes-command-center, draft outreach for ${top[0].business} and save it under local-ai-drafts/."`]];
 $('#app').innerHTML=metrics()+`<section class="strategy-hero"><p class="eyebrow">Integrated agency operating system</p><h2>One hub for command center, public website, demos, pitch kits, close rooms, local AI, and deploy prep.</h2><p>The default path is local-first and script-first: use zero-model generators for repeatable production, local Ollama for rough content, and Codex only for premium architecture/final review.</p><div class="strategy-actions"><button onclick="location.hash='war'">Work leads</button><button onclick="location.hash='usage'">Open Usage Saver</button><a href="./public-site/index.html">Public website</a></div></section><div class="grid cols-5 ops-grid">${ops.map((o,i)=>`<div class="card ops-lane"><em>0${i+1}</em><h2>${o[0]}</h2><p class="muted">${o[1]}</p></div>`).join('')}</div><div class="split"><div class="card"><h2>Next three money moves</h2>${top.map((l,i)=>`<div class="proof-item"><div class="proof-dot"></div><div><b>${i+1}. ${esc(l.business)}</b><br><span class="muted">${esc(l.offer)} · ${fmt(l.estBookings*l.avgValue)}/mo upside · <a href="./close-rooms/${l.id}.html">close room</a></span></div></div>`).join('')}</div><div class="card"><h2>Full-system commands</h2><p class="muted">These wire command centers, websites, demos, briefings, and deploy assets together.</p>${commands.map(([label,cmd])=>`<div class="cmd-row"><div><b>${label}</b><code>${esc(cmd)}</code></div><button onclick="copy('${cmd.replace(/\\/g,'\\\\').replace(/'/g,"\\'")}')">Copy</button></div>`).join('')}</div></div>`;
}

function intelligence(){
 const p=state.premium, top=state.leads.slice().sort((a,b)=>(b.score-a.score)||(upside(b)-upside(a))).slice(0,4);
 const lanes=p.operatingSystem;
 const packets=p.dealPackets;
 const studio=p.higgsfieldStudio;
 const totalPipe=state.leads.reduce((a,l)=>a+upside(l),0);
 const medPipe=state.leads.filter(l=>l.industry==='Medspa').reduce((a,l)=>a+upside(l),0);
 $('#app').innerHTML=`<section class="intel-shell">
  <div class="intel-hero">
    <div><p class="eyebrow">Premier rebuild layer</p><h2>The revenue command room for Stratos.</h2><p>${esc(p.positioning.coreThesis)}</p><div class="intel-actions"><button onclick="location.hash='war'">Work pipeline</button><button onclick="location.hash='outreach'">Send outreach</button><a href="./STRATOS_PREMIUM_REBUILD_BLUEPRINT.md">Blueprint</a><a href="./HIGGSFIELD_CREATIVE_STUDIO.md">Higgsfield studio</a></div></div>
    <aside class="intel-verdict"><span>Current verdict</span><b>Strong bones. Premium layer still matters.</b><small>${esc(p.repoAuditFindings[1])}</small><div class="verdict-list"><div><strong>Next sale</strong><em>Medspa concierge</em></div><div><strong>Creative</strong><em>Credit-blocked, prompts ready</em></div><div><strong>Ship mode</strong><em>Static / Vercel-safe</em></div></div></aside>
  </div>
  <div class="intel-scoreboard">
    <div class="intel-score primary"><span>Total pipeline</span><b>${fmt(totalPipe)}</b><small>Opportunity math from current lead board</small></div>
    <div class="intel-score"><span>Medspa wedge</span><b>${fmt(medPipe)}</b><small>Primary market attack lane</small></div>
    <div class="intel-score"><span>Higgsfield</span><b>0 credits</b><small>Ready-to-run studio prepared; generation blocked</small></div>
    <div class="intel-score"><span>Proof discipline</span><b>${p.proofLedger.statuses.length} stages</b><small>Demo → result guardrails embedded</small></div>
  </div>
  <div class="quality-wall">${p.positioning.qualityBar.map((q,i)=>`<div><span>Q${i+1}</span><p>${esc(q)}</p></div>`).join('')}</div>
  <div class="section-title"><h2>Operating lanes</h2><p>Every module now rolls up into one of these command lanes.</p></div>
  <div class="lane-grid">${lanes.map(l=>`<article class="lane-card"><p class="eyebrow">${esc(l.lane)}</p><h2>${esc(l.goal)}</h2><ul>${l.dailyMoves.slice(0,3).map(m=>`<li>${esc(m)}</li>`).join('')}</ul><div class="lane-metric"><b>Measure</b><span>${esc(l.ownerMetric)}</span></div><details class="failure-mode"><summary>Failure mode</summary><span>${esc(l.failureMode)}</span></details></article>`).join('')}</div>
  <div class="split premium-split"><div class="card deal-command"><h2>Deal packet router</h2><p class="muted">Use these as the prospect-specific sales spine before writing anything custom.</p>${packets.map(d=>`<details class="deal-packet"><summary><span>${esc(d.vertical)}</span><b>${esc(d.flagshipOffer)}</b><em>${esc(d.recommendedPackage)}</em></summary><p>${esc(d.firstTouch)}</p><div class="trigger-list">${d.triggerSignals.map(s=>`<span>${esc(s)}</span>`).join('')}</div><div class="sales-line">${esc(d.closeRoomPromise)}</div></details>`).join('')}</div><div class="card"><h2>Today’s boardroom targets</h2>${top.map((l,i)=>`<div class="boardroom-target"><span>${String(i+1).padStart(2,'0')}</span><div><b>${esc(l.business)}</b><p>${esc(l.industry)} · ${fmt(upside(l))}/mo upside · ${esc(l.angle)}</p></div><button onclick="selectLead('${l.id}'); location.hash='audit'">Audit</button></div>`).join('')}</div></div>
  <div class="split premium-split"><div class="card proof-rules"><h2>Proof ledger rules</h2>${p.proofLedger.rules.map(r=>`<div class="proof-rule">${esc(r)}</div>`).join('')}<h3>Capture checklist</h3><div class="trigger-list">${p.proofLedger.captureChecklist.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div><div class="card higgs-panel"><h2>Higgsfield Studio</h2><p class="muted">${esc(studio.currentStatus)}</p>${studio.modelPlan.map(m=>`<div class="model-plan"><b>${esc(m.asset)}</b><span>${esc(m.model)} · ${esc(m.format)}</span><small>${esc(m.post)}</small></div>`).join('')}<button onclick="location.hash='repurpose'">Use content engine</button></div></div>
 </section>`;
}

function upside(l){return (l.estBookings||0)*(l.avgValue||0)}
function industryStats(){
 const map={}; state.leads.forEach(l=>{map[l.industry]=map[l.industry]||{count:0,upside:0,score:0}; map[l.industry].count++; map[l.industry].upside+=upside(l); map[l.industry].score+=l.score;});
 return Object.entries(map).map(([name,v])=>({name,...v,avg:Math.round(v.score/v.count)})).sort((a,b)=>b.upside-a.upside);
}
function warMetricCards(leads=state.leads){
 const sorted=leads.slice().sort((a,b)=>b.score-a.score), top=sorted[0]||{}, hot=leads.filter(l=>l.score>=88), pipe=leads.reduce((a,l)=>a+upside(l),0), avg=Math.round(leads.reduce((a,l)=>a+l.score,0)/(leads.length||1));
 const medspa=leads.filter(l=>l.industry==='Medspa').reduce((a,l)=>a+upside(l),0);
 return `<div class="war-metrics">
  <div class="war-metric primary"><span>Pipeline upside</span><strong data-count="${pipe}">${fmt(pipe)}</strong><small>Monthly opportunity from current board</small></div>
  <div class="war-metric"><span>Priority lead</span><strong>${esc(top.business||'None')}</strong><small>${top.score||0} score · ${fmt(upside(top))}/mo</small></div>
  <div class="war-metric"><span>Hot targets</span><strong>${hot.length}/${leads.length}</strong><small>Score 88+ ready for first touch</small></div>
  <div class="war-metric"><span>Average score</span><strong>${avg}</strong><small>Board quality signal</small></div>
  <div class="war-metric"><span>Medspa upside</span><strong>${fmt(medspa)}</strong><small>Primary vertical focus</small></div>
 </div>`;
}
function scoreTone(score){return score>=90?'elite':score>=88?'hot':'warm'}
function intentLabel(l){return l.score>=90?'Send today':l.industry==='Medspa'?'Medspa lane':'Nurture'}
function war(){
 const industries=industryStats();
 $('#app').innerHTML=`<section class="war-room">
  <div class="war-hero reveal-card">
    <div><p class="eyebrow">Clean attack view</p><h2>Less clutter. More signal.</h2><p>Prioritize the highest-upside Boca businesses, see why they matter, and jump straight into pitch kits or private close rooms.</p></div>
    <div class="war-hero-panel"><span>Next best action</span><b>${esc(state.leads.slice().sort((a,b)=>b.score-a.score)[0]?.business||'Top lead')}</b><small>Open pitch kit → send concise first touch → attach close room.</small><button onclick="selectLead('${state.leads.slice().sort((a,b)=>b.score-a.score)[0]?.id||''}'); location.hash='pitch'">Build pitch</button></div>
  </div>
  ${warMetricCards()}
  <div class="war-layout">
    <aside class="war-control reveal-card">
      <div class="control-head"><span>Filters</span><button id="resetWar">Reset</button></div>
      <label>Industry</label><select id="industry"><option>All industries</option>${industries.map(i=>`<option>${esc(i.name)}</option>`).join('')}</select>
      <label>Search</label><input id="search" placeholder="Business, offer, weakness...">
      <label>Minimum score</label><input id="minScore" type="range" min="80" max="95" value="86"><div class="range-readout"><span>Show score ≥</span><b id="scoreReadout">86</b></div>
      <div class="vertical-stack"><h3>Vertical signal</h3>${industries.map(i=>`<button class="industry-chip" data-industry="${esc(i.name)}"><span>${esc(i.name)}</span><b>${fmt(i.upside)}</b><small>${i.count} leads · avg ${i.avg}</small></button>`).join('')}</div>
    </aside>
    <section class="war-board">
      <div class="board-top"><div><h2>Priority board</h2><p id="resultCount">${state.leads.length} leads</p></div><div class="sort-pill">Sorted by score + upside</div></div>
      <div id="leadCards" class="lead-cards"></div>
    </section>
  </div>
 </section>`;
 const draw=()=>{
  const q=$('#search').value.toLowerCase().trim(), ind=$('#industry').value, min=+$('#minScore').value; $('#scoreReadout').textContent=min;
  const rows=state.leads.filter(l=>(ind==='All industries'||l.industry===ind)&&l.score>=min&&[l.business,l.industry,l.offer,l.angle,...l.weaknesses].join(' ').toLowerCase().includes(q)).sort((a,b)=>(b.score-a.score)||(upside(b)-upside(a)));
  $('#resultCount').textContent=`${rows.length} lead${rows.length===1?'':'s'} visible`;
  $('#leadCards').innerHTML=rows.map((l,i)=>`<article class="lead-card ${scoreTone(l.score)}" style="--delay:${Math.min(i,8)*42}ms">
    <div class="lead-main"><div><span class="rank">#${i+1}</span><h3>${esc(l.business)}</h3><p>${esc(l.industry)} · ${esc(l.address)}</p></div><div class="score-ring" style="--score:${l.score}"><span>${l.score}</span></div></div>
    <div class="lead-kpis"><div><span>Upside</span><b>${fmt(upside(l))}/mo</b></div><div><span>Bookings</span><b>${l.estBookings}</b></div><div><span>Avg value</span><b>${fmt(l.avgValue)}</b></div></div>
    <div class="lead-focus"><span>${esc(intentLabel(l))}</span><p>${esc(l.weaknesses[0])}</p></div>
    <div class="offer-strip"><b>${esc(l.offer)}</b><small>${esc(l.angle)}</small></div>
    <div class="lead-actions"><button onclick="selectLead('${l.id}'); location.hash='pitch'">Pitch kit</button><a class="inline-link" href="./close-rooms/${l.id}.html">Close room</a><a class="inline-link subtle" href=".${l.demo}">Demo</a></div>
  </article>`).join('') || `<div class="empty-board"><b>No leads match this filter.</b><span>Lower the score threshold or reset filters.</span></div>`;
 };
 $('#search').oninput=draw; $('#industry').onchange=draw; $('#minScore').oninput=draw; $('#resetWar').onclick=()=>{$('#industry').value='All industries'; $('#search').value=''; $('#minScore').value=86; draw();};
 document.querySelectorAll('.industry-chip').forEach(b=>b.onclick=()=>{$('#industry').value=b.dataset.industry; draw();});
 draw();
}
function demos(){ const gallery=state.growth.demoGallery; $('#app').innerHTML=sectionIntro('Proof you can show','A vertical demo gallery prospects can understand in one glance.','Each card explains what the demo fixes, then links to existing generated demo/close-room assets.',`<a class="inline-link" href="./public-site/index.html">View public Stratos site</a>`)+`<div class="demo-grid premium-demo-grid">${gallery.map(g=>`<div class="card demo-card premium-demo"><div class="preview"><div class="bar w90"></div><div class="bar w70"></div><div class="bar w45"></div></div><p class="eyebrow">${esc(g.vertical)}</p><h2>${esc(g.concept)}</h2><p class="muted">${esc(g.whatItFixes)}</p><a class="inline-link" href="${esc(g.demoPath)}">Open demo</a></div>`).join('')}</div><div class="section-title"><h2>Lead-specific demo assets</h2><p>Current generated demos and private close rooms.</p></div><div class="demo-grid">${state.leads.map(l=>`<div class="card demo-card"><h2>${esc(l.business)}</h2><p class="muted">${esc(l.industry)}: ${esc(l.angle)}</p><p><span class="pill">AI booking</span><span class="pill">Lead capture</span><span class="pill">Before/after audit</span></p><a class="inline-link" href=".${l.demo}">Open demo</a> · <a class="inline-link" href="./close-rooms/${l.id}.html">Close room</a></div>`).join('')}</div>`; }
function pitchText(l=state.selected){return `SUBJECT: Quick ${l.industry.toLowerCase()} growth idea for ${l.business}\n\nHey ${l.business} team — I was looking at your online booking and lead flow and noticed an opportunity: ${l.weaknesses[0].toLowerCase()}.\n\nI run Stratos AI. We build premium local-business sites with AI booking, missed-call recovery, review automation, and follow-up systems. For ${l.business}, I’d recommend: ${l.offer}.\n\nWhy it fits:\n- ${l.weaknesses.join('\n- ')}\n\nThe angle: ${l.angle}\n\nI can send a quick preview/mockup showing what this would look like with your brand. If it doesn’t feel useful, no worries.\n\n— Bradley\nStratos AI\n\nSMS/DM: Saw a couple ways ${l.business} could capture more ${l.industry.toLowerCase()} leads with AI booking + follow-up. Want me to send the quick preview?\n\nCALL OPENER: I’m local to Boca and built a quick growth-system concept for ${l.business}. The main idea is ${l.angle}\n\nLINKS:\nDemo: .${l.demo}\nClose room: ./close-rooms/${l.id}.html`}
function pitch(){ $('#app').innerHTML=`<div class="split"><div class="card"><h2>Pitch kit generator</h2><p class="muted">Select a lead. The pack generates email, SMS, DM, phone opener, pain points, offer, and demo/proposal CTA.</p><select id="leadSelect">${leadOptions()}</select><div style="height:14px"></div><textarea id="customNote" placeholder="Optional extra context for this lead"></textarea><div style="height:14px"></div><button id="genPitch">Regenerate Pack</button></div><div class="card"><h2>${esc(state.selected.business)}</h2><p class="muted">${esc(state.selected.angle)}</p><div id="pitchOut" class="pitch-output"></div></div></div>`; $('#leadSelect').value=state.selected.id; const gen=()=>{$('#pitchOut').textContent=pitchText(state.selected)+($('#customNote').value?`\n\nCUSTOM NOTE: ${$('#customNote').value}`:'')}; $('#leadSelect').onchange=e=>{selectLead(e.target.value); pitch()}; $('#genPitch').onclick=gen; gen(); }
function workflow(){ $('#app').innerHTML=`<div class="card"><h2>The main money workflow</h2><p class="muted">Every asset supports this one sequence: Scan → Audit → Demo → Pitch → Close → Fulfill → Prove.</p></div><div class="workflow" style="margin-top:16px">${[['Scan','Find real Boca leads'],['Audit','Score site + funnel gaps'],['Demo','Generate specific rebuild'],['Pitch','Send one-click pack'],['Close','Private proposal room'],['Fulfill','Website + AI automations'],['Prove','Proof vault + case study']].map((s,i)=>`<div class="step"><em>Step ${i+1}</em><strong>${s[0]}</strong><p class="muted">${s[1]}</p></div>`).join('')}</div><div class="section-title"><h2>Pipeline</h2></div><div class="pipeline">${['New','Contacted','Responded','Meeting','Closed'].map((stage,i)=>`<div class="stage"><h3>${stage}</h3>${i===0?state.leads.slice(0,4).map(l=>`<div class="mini-card"><b>${esc(l.business)}</b><br><span class="muted">${esc(l.offer)}</span></div>`).join(''):'<p class="muted">Waiting for movement.</p>'}</div>`).join('')}</div>`; }
function medspa(){
 const meds=state.leads.filter(l=>l.industry==='Medspa'); const c=state.growth.medspaCampaign;
 $('#app').innerHTML=sectionIntro('Primary wedge campaign','MedSpa Growth OS: the fastest vertical to make Stratos feel premium and specific.','Aesthetic clinics sell high-trust, high-LTV services. The Stratos angle is not generic AI — it is consult capture, premium treatment journeys, proof sequencing, and follow-up.',`<button onclick="location.hash='outreach'">Use medspa scripts</button>`)+`<div class="grid cols-3" style="margin-top:16px"><div class="card"><h2>Positioning</h2><p class="muted">${esc(c.positioning)}</p><h3>Pain signals</h3>${c.painSignals.map(x=>`<div class="mini-card">${esc(x)}</div>`).join('')}</div><div class="card"><h2>Hooks to test</h2>${c.hooks.map(x=>`<div class="mini-card"><b>${esc(x)}</b></div>`).join('')}<div class="sales-line" style="margin-top:12px">${esc(c.demoOffer)}</div></div><div class="card"><h2>Medspa targets</h2>${meds.map(l=>`<div class="mini-card"><b>${esc(l.business)}</b><br><span class="muted">${esc(l.phone)} · Score ${l.score} · ${fmt(upside(l))}/mo upside</span></div>`).join('')}<button onclick="selectLead('${meds[0]?.id||state.leads[0].id}'); location.hash='audit'">Audit first target</button></div></div>`;
}
function revenue(){ $('#app').innerHTML=`<div class="split"><div class="card"><h2>Revenue forecast simulator</h2><p class="muted">Uses each lead’s estimated bookings and average value. Adjust live to make the ROI argument.</p><select id="leadSelect">${leadOptions()}</select><label class="muted">New bookings / month</label><input id="bookings" type="number"><label class="muted">Avg customer value</label><input id="value" type="number"><label class="muted">Stratos monthly fee</label><input id="fee" type="number" value="1500"></div><div class="card" id="roiOut"></div></div>`; $('#leadSelect').value=state.selected.id; const calc=()=>{const rev=+$('#bookings').value*+$('#value').value, fee=+$('#fee').value, roi=fee?(rev/fee).toFixed(1):'0.0'; $('#roiOut').innerHTML=`<h2>${esc(state.selected.business)}</h2><div class="roi"><span>Estimated added monthly revenue</span><b>${fmt(rev)}</b></div><div class="roi"><span>Stratos retainer</span><b>${fmt(fee)}</b></div><div class="roi"><span>ROI multiple</span><b>${roi}x</b></div><p class="muted">Pitch line: if this creates even ${Math.ceil(fee/(+$('#value').value||1))} extra bookings, the system pays for itself.</p>`}; $('#leadSelect').onchange=e=>{selectLead(e.target.value); revenue()}; $('#bookings').value=state.selected.estBookings; $('#value').value=state.selected.avgValue; ['bookings','value','fee'].forEach(id=>$('#'+id).oninput=calc); calc(); }
function briefing(){ const top=state.leads.slice().sort((a,b)=>b.score-a.score).slice(0,5); $('#app').innerHTML=`<div class="card"><p class="eyebrow">Morning Briefing</p><h2>Today’s highest-leverage moves</h2><p class="muted">Generated from the current War Room. No fake responses; this is task guidance until real integrations are connected.</p><a class="inline-link" href="./briefings/latest.md">Open generated briefing file</a></div><div class="grid cols-2" style="margin-top:16px"><div class="card"><h2>Top 5 targets</h2>${top.map((l,i)=>`<div class="proof-item"><div class="proof-dot"></div><div><b>${i+1}. ${esc(l.business)}</b><br><span class="muted">Score ${l.score}. Move: ${esc(l.angle)}</span></div></div>`).join('')}</div><div class="card"><h2>Action queue</h2>${['Generate Glamor Medical close room','Run audits for top 5','Send first pitch kits','Create Vercel preview for public portfolio','Persist leads to production data store'].map(x=>`<div class="mini-card">${x}</div>`).join('')}</div></div>`; }
function proof(){ $('#app').innerHTML=`<div class="grid cols-3"><div class="card metric"><span>Demo builds</span><b>${state.leads.length}</b></div><div class="card metric"><span>Close rooms</span><b>${state.leads.length}</b></div><div class="card metric"><span>Outreach sent</span><b>0</b></div></div><div class="section-title"><h2>Proof Vault</h2><p>Wins, demos, screenshots, proposals, outreach, and case-study material.</p></div><div class="card">${state.leads.slice(0,5).map(l=>`<div class="proof-item"><div class="proof-dot"></div><div><b>${esc(l.business)} demo + close-room assets</b><br><span class="muted">Status: concept ready · Needs screenshot/audit capture · ${esc(l.demo)}</span></div></div>`).join('')}</div>`; }
function portfolio(){ $('#app').innerHTML=`<div class="hero-public"><p class="eyebrow">Public Stratos Page</p><h2>Premium AI websites and automation systems for local businesses.</h2><p>Turn missed calls, weak websites, and cold traffic into booked appointments with AI lead capture, follow-up, reviews, and conversion-focused design.</p><a href="./public-site/index.html">Open generated public site</a></div><div class="grid cols-3" style="margin-top:16px">${['Premium website rebuilds','AI booking systems','Review + referral engines'].map(x=>`<div class="card"><h2>${x}</h2><p class="muted">Built for Boca businesses that need measurable lead capture, not generic web design.</p></div>`).join('')}</div>`; }
function close(){ $('#app').innerHTML=`<div class="split"><div class="close-room"><p class="eyebrow">Private Proposal Room</p><h2>${esc(state.selected.business)}</h2><p>${esc(state.selected.angle)}</p><div class="grid cols-2"><div class="roi"><span>Projected upside</span><b>${fmt(state.selected.estBookings*state.selected.avgValue)}/mo</b></div><div class="roi"><span>Recommended offer</span><b>${esc(state.selected.offer)}</b></div></div><h3>What we found</h3>${state.selected.weaknesses.map(w=>`<span class="pill">${esc(w)}</span>`).join('')}<h3>Investment</h3><div class="price">$2,500 setup + $1,500/mo</div><a href="./close-rooms/${state.selected.id}.html">Open generated close room</a> <button onclick="location.hash='pitch'">Generate outreach</button></div><div class="card"><h2>Launch plan</h2>${['48-hour audit and conversion map','7-day custom demo/proposal page','14-day launch of site + AI capture','30-day optimization and reporting'].map((x,i)=>`<div class="proof-item"><div class="proof-dot"></div><div><b>Phase ${i+1}</b><br><span class="muted">${x}</span></div></div>`).join('')}</div></div>`; }
function usage(){
 const zero=['Generate demo pages from data','Build outreach pitch kits','Generate close rooms','Build public website','Create deploy manifest','Validate dashboard + data'];
 const cheap=['Draft first-pass outreach variants with Ollama','Summarize scraped websites locally','Classify leads by vertical','Rewrite blurbs using qwen3.5:9b'];
 const premium=['Architecture decisions','Complex debugging','Final product/design review','Multi-file refactors'];
 const commands=[['Full rebuild/test','python3 scripts/run_all.py'],['Validate without AI','python3 scripts/validate_dashboard.py'],['Generate all demo pages','python3 scripts/generate_demo_pages.py'],['Build pitch kits','python3 scripts/build_pitch_kits.py'],['Generate close rooms','python3 scripts/generate_close_rooms.py'],['Build public site','python3 scripts/build_public_site.py'],['Check local Ollama','python3 scripts/ollama_health.py'],['Draft with qwen3.5 locally','python3 scripts/ollama_draft.py --lead glamor-medical --mode all'],['Run on free port','python3 scripts/free_port_server.py --start 8790']];
 $('#app').innerHTML=`<div class="usage-hero"><p class="eyebrow">Quota Defense System</p><h2>Make Hermes feel endless by routing work to the cheapest capable lane.</h2><p>Codex stays reserved for architecture, hard debugging, and final review. Everything repeatable becomes scripts or cheap-model drafting.</p></div><div class="grid cols-3" style="margin-top:16px"><div class="card usage-card zero"><span>Tier 0</span><h2>Free Script</h2><p class="muted">No model calls. Use this for deterministic Stratos production work.</p>${zero.map(x=>`<div class="mini-card">${x}</div>`).join('')}</div><div class="card usage-card cheap"><span>Tier 1</span><h2>Cheap Draft</h2><p class="muted">Use local Ollama models for volume writing and classification without Codex quota.</p>${cheap.map(x=>`<div class="mini-card">${x}</div>`).join('')}</div><div class="card usage-card premium"><span>Tier 2</span><h2>Premium Review</h2><p class="muted">Use Codex/GPT-5.5 only when judgment quality matters most.</p>${premium.map(x=>`<div class="mini-card">${x}</div>`).join('')}</div></div><div class="split" style="margin-top:16px"><div class="card"><h2>Zero/local command deck</h2><p class="muted">Copy these into Terminal. Script commands spend no AI quota; Ollama commands run locally on your Mac.</p>${commands.map(([label,cmd])=>`<div class="cmd-row"><div><b>${label}</b><code>${esc(cmd)}</code></div><button onclick="copy('${cmd.replace(/\\/g,'\\\\').replace(/'/g,"\\'")}')">Copy</button></div>`).join('')}</div><div class="card"><h2>Quota routing log</h2><div class="quota-log"><div><b>Lead/demo generation</b><span>Free Script</span></div><div><b>Pitch + close-room generation</b><span>Free Script</span></div><div><b>Outreach copy variants</b><span>Local Ollama</span></div><div><b>Local models</b><span>qwen3.5:9b + qwen2.5-coder:7b</span></div><div><b>Dashboard architecture</b><span>Premium Review only</span></div><div><b>Browser smoke test</b><span>One pass after changes</span></div></div><p class="muted">Default Codex profile remains premium mode. Use <code>hermes -p stratos-local</code> for local drafts.</p></div></div>`;
}

function firstLeadByIndustry(industry){return state.leads.find(l=>l.industry===industry)||state.leads[0]}
function fillTemplate(t,l=state.selected){return esc(String(t||'').replaceAll('{{business}}',l.business).replaceAll('{{industry}}',l.industry).replaceAll('{{weakness}}',l.weaknesses?.[0]||'lead capture can be sharper').replaceAll('{{angle}}',l.angle).replaceAll('{{offer}}',l.offer))}
function sectionIntro(kicker,title,body,action){return `<section class="growth-hero"><div><p class="eyebrow">${esc(kicker)}</p><h2>${esc(title)}</h2><p>${esc(body)}</p></div>${action?`<div class="growth-hero-action">${action}</div>`:''}</section>`}
function today(){
 const moves=state.growth.todayMoves;
 const top=state.leads.slice().sort((a,b)=>b.score-a.score).slice(0,4);
 $('#app').innerHTML=sectionIntro('Built for today','Six concrete moves to create pipeline, proof, and sharper offers before tomorrow.','This is the daily operator board: no fake numbers, no vague strategy, just the actions that move Stratos toward conversations and closed work.',`<button onclick="location.hash='outreach'">Open scripts</button><button onclick="location.hash='offers'">Open offers</button>`)+`<div class="today-layout"><div class="today-list">${moves.map((m,i)=>`<article class="today-card"><div class="today-num">${String(i+1).padStart(2,'0')}</div><div><span class="priority">${esc(m.priority)} · ${esc(m.timebox)}</span><h2>${esc(m.title)}</h2><p>${esc(m.outcome)}</p><ul>${m.actions.map(a=>`<li>${esc(a)}</li>`).join('')}</ul><small>${esc(m.proof)}</small></div></article>`).join('')}</div><aside class="card focus-panel"><h2>Start here</h2>${top.map((l,i)=>`<div class="mini-card"><b>${i+1}. ${esc(l.business)}</b><br><span class="muted">${esc(l.industry)} · ${esc(l.offer)} · ${fmt(upside(l))}/mo upside</span></div>`).join('')}<button onclick="location.hash='pitch'">Generate first touch</button></aside></div>`;
}
function offers(){
 const offers=state.growth.offerLadder;
 $('#app').innerHTML=sectionIntro('Sellable packages','A clean $3k / $5k / $10k offer ladder with a retainer path.','These packages make Stratos easier to explain, easier to price, and easier to upsell without custom proposal chaos.',`<button onclick="location.hash='closeTemplates'">Use in close rooms</button>`)+`<div class="offer-ladder">${offers.map((o,i)=>`<article class="offer-card"><div class="offer-head"><span>0${i+1}</span><strong>${esc(o.price)}</strong></div><h2>${esc(o.name)}</h2><p>${esc(o.promise)}</p><div class="fit"><b>Best for</b><span>${esc(o.bestFor)}</span></div><h3>Deliverables</h3><ul>${o.deliverables.map(d=>`<li>${esc(d)}</li>`).join('')}</ul><div class="sales-line">${esc(o.salesLine)}</div><small>Next step: ${esc(o.upsell)}</small></article>`).join('')}</div>`;
}
function outreach(){
 const g=state.growth.outreachVault, l=state.selected;
 const verticals=['Medspa','Dental','Plumbing','HVAC','Legal','Auto'];
 $('#app').innerHTML=sectionIntro('Ready-to-send copy','Outreach scripts that feel specific without pretending we have fake results.','Select a lead, then copy the channel that fits: DM, email, follow-up, Loom, or phone opener.',`<select id="leadSelect">${leadOptions()}</select>`)+`<div class="script-grid"><div class="card script-card"><h2>DM opener</h2><pre>${fillTemplate(g.dmShort,l)}</pre><button onclick="copy(\`${fillTemplate(g.dmShort,l)}\`)">Copy DM</button></div><div class="card script-card wide"><h2>Email first touch</h2><pre>${fillTemplate(g.emailFirstTouch,l)}</pre><button onclick="copy(\`${fillTemplate(g.emailFirstTouch,l)}\`)">Copy email</button></div><div class="card script-card"><h2>Loom script</h2><pre>${fillTemplate(g.loomScript,l)}</pre><button onclick="copy(\`${fillTemplate(g.loomScript,l)}\`)">Copy Loom</button></div><div class="card script-card"><h2>Phone opener</h2><pre>${fillTemplate(g.phoneOpener,l)}</pre><button onclick="copy(\`${fillTemplate(g.phoneOpener,l)}\`)">Copy phone</button></div><div class="card script-card wide"><h2>Follow-up sequence</h2>${g.followUps.map((f,i)=>`<div class="mini-card followup-row"><div><b>Follow-up ${i+1}</b><br><span>${fillTemplate(f,l)}</span></div><button onclick="copy(\`${fillTemplate(f,l)}\`)">Copy</button></div>`).join('')}</div><div class="card"><h2>Vertical defaults</h2>${verticals.map(v=>{const lead=firstLeadByIndustry(v);return `<button class="industry-chip" onclick="selectLead('${lead.id}'); outreach()"><span>${esc(v)}</span><small>${esc(lead.business)}</small></button>`}).join('')}</div></div>`;
 $('#leadSelect').value=state.selected.id; $('#leadSelect').onchange=e=>{selectLead(e.target.value); outreach()};
}
function audit(){
 const checks=state.growth.auditGenerator.checks, l=state.selected;
 $('#app').innerHTML=sectionIntro('Client Audit Generator','Turn a website scan into a precise, useful sales asset.','Use this before Looms, emails, or close rooms. The goal is to diagnose the front-door leak and recommend the first practical fix.',`<select id="leadSelect">${leadOptions()}</select>`)+`<div class="audit-grid"><div class="audit-checks">${checks.map((c,i)=>`<article class="audit-card"><span>0${i+1}</span><h2>${esc(c.area)}</h2><p><b>Question:</b> ${esc(c.question)}</p><p><b>Fix:</b> ${esc(c.fix)}</p><button onclick="copy('${c.area.replace(/'/g,"\\'")}: ${c.fix.replace(/'/g,"\\'")}')">Copy fix</button></article>`).join('')}</div><aside class="card audit-summary"><h2>${esc(l.business)} quick summary</h2><p>${esc(state.growth.auditGenerator.summaryTemplate.replace('{{business}}',l.business).replace('{{area}}',checks[0].area).replace('{{weakness}}',l.weaknesses[0].toLowerCase()).replace('{{fix}}',checks[0].fix.toLowerCase()))}</p><h3>Lead-specific signals</h3>${l.weaknesses.map(w=>`<span class="pill">${esc(w)}</span>`).join('')}<button onclick="location.hash='pitch'">Turn into pitch</button></aside></div>`;
 $('#leadSelect').value=state.selected.id; $('#leadSelect').onchange=e=>{selectLead(e.target.value); audit()};
}
function closeTemplates(){
 const templates=state.growth.closeRoomTemplates;
 $('#app').innerHTML=sectionIntro('Private proposal rooms','Four close-room structures for the verticals Stratos can sell first.','Each template keeps the proposal simple: diagnose the leak, show the system, anchor investment, and ask for the next step.',`<button onclick="location.hash='close'">Open live close room</button>`)+`<div class="template-grid">${templates.map(t=>`<article class="template-card"><p class="eyebrow">${esc(t.vertical)}</p><h2>${esc(t.headline)}</h2><div class="template-sections">${t.sections.map(s=>`<span>${esc(s)}</span>`).join('')}</div><div class="cta-strip">${esc(t.cta)}</div></article>`).join('')}</div>`;
}
function repurpose(){
 const rows=state.growth.repurposingEngine;
 $('#app').innerHTML=sectionIntro('Content multiplier','Turn one Stratos asset into LinkedIn, X, email hooks, and reel prompts.','This keeps content output high without making every post look like the same AI template.',`<a class="inline-link" href="./marketing-assets/instagram-month-pack-v2/CONTENT_CALENDAR.md">Open calendar</a>`)+`<div class="repurpose-grid">${rows.map((r,i)=>`<article class="card repurpose-card"><span class="priority">Source ${i+1}: ${esc(r.source)}</span><h2>Repurpose stack</h2><div class="channel"><b>LinkedIn</b><p>${esc(r.linkedin)}</p></div><div class="channel"><b>X</b><p>${esc(r.x)}</p></div><div class="channel"><b>Email hook</b><p>${esc(r.emailHook)}</p></div><div class="channel"><b>Reel prompt</b><p>${esc(r.reelPrompt)}</p></div></article>`).join('')}</div>`;
}
function cases(){
 const rows=state.growth.caseStudies;
 $('#app').innerHTML=sectionIntro('Transparent proof builder','Demo case studies that explain value without inventing client results.','Use these in outbound and close rooms as clearly-labeled examples until real client outcomes exist.',`<button onclick="location.hash='proof'">Open Proof Vault</button>`)+`<div class="case-grid">${rows.map(c=>`<article class="case-card"><span>${esc(c.label)}</span><h2>${esc(c.title)}</h2><div class="before-after"><div><b>Before</b><p>${esc(c.before)}</p></div><div><b>After</b><p>${esc(c.after)}</p></div></div><h3>Assets to show</h3>${c.assets.map(a=>`<span class="pill">${esc(a)}</span>`).join('')}<p class="guardrail"><b>Guardrail:</b> ${esc(c.claimGuardrail)}</p></article>`).join('')}</div>`;
}

function exportSnapshot(){ const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),leads:state.leads,automations:state.automations},null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='stratos-command-snapshot.json'; a.click(); toast('Snapshot exported.'); }
init().catch(err=>{document.body.innerHTML='<pre>'+err.stack+'</pre>';});
